### ISSUE TITLE
NuGet don't want to install Dynamo ...

### ISSUE THREAD

**Issue by catafest** [DynamoDS/DynamoText#8]
I try to install Dynamo, starting with DynamoVisualProgramming.DynamoServices.
The NuGet package manager doesn't want to install the DynamoVisualProgramming.DynamoServices.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'DynamoVisualProgramming.DynamoServices 2.5.0.7432'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		
```

**Comment by mjkkirschner** [comment]
change your project to target .net 4.7 or above.
https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview?view=vs-2019

**Comment by catafest** [comment]
... thanks. fixed!
